/// Flutter icons NeuropathyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NeuropathyIcons
///      fonts:
///       - asset: fonts/NeuropathyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NeuropathyIcons {
  NeuropathyIcons._();

  static const _kFontFam = 'NeuropathyIcons';
  static const String? _kFontPkg = null;

  static const IconData bxs_mobile_vibration = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bi_bandaid_fill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maki_doctor = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carbon_result = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_park_foot = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ph_needle_fillprick_needle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
